### PR TITLE
Added Sublime, removed Notepad++

### PR DESCRIPTION
**Pull request by towerofnix**
There are SOOOOO many better choices out there than Notepad++ (plus you can basically customize most good editors to look like Notepad++ and/or use Notepad++ keybindings).

### CODE REVIEW

**Comment by PullJosh** [comment]
I removed sublime yesterday. :P
223d6adeda36732be6de1f0d6bf7bcb293ca17b1

https://scratch.mit.edu/discuss/topic/167780/?page=1#post-1597833
But I'll remove n++

**Comment by towerofnix** [comment]
ah ok :P

**Comment by towerofnix** [comment]
Looking back on this I think I didn't know the difference between [Notepad](http://www.internet4classrooms.com/notepad_small_window.gif) and [Notepad++](http://getintopc.com/wp-content/uploads/2013/07/download-notepad++-free-latest-setup.jpg). Oops.

**Comment by PullJosh** [comment]
:package:

**Pull request closed without merging**
