### PR TITLE
Remember gwiddle plz

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jeandrek** [comment]
Yes
waek up @PullJosh

**Comment by ghost** [comment]
Plzgwiddlepl0x

**Comment by PullJosh** [comment]
If you add [github pages](https://pages.github.com/) as well, I'll merge.

**Comment by ghost** [comment]
Oh, ok then :stuck_out_tongue:

**Comment by ghost** [comment]
Done

**Comment by ghost** [comment]
Åslañæßøtrgêëê!
I summon @PullJosh to kamm hier und check this
Åßlåsoløvíkjånhoerd
And i summon Thisandagain to explain :P

**Comment by PullJosh** [comment]
Think you could change the test from "Github based hosting" to "Free and fast hosting with no backend"?

**Comment by ghost** [comment]
Oh, ok then :P

**Comment by ghost** [comment]
Done

**Comment by PullJosh** [comment]
Okay, cool! Thanks for the help! :D

**Pull request merged**
